version: '3'
services:
  typesense:
    image: typesense/typesense:28.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: >
      --data-dir /data
      --api-key=${TYPESENSE_INTERNAL_API_KEY}
      --enable-cors
    env_file:
      - .env
