name: Format and Validate HTML
on: [push, pull_request]
jobs:
  format-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git-auto-commit-action

      # 1. Setup Node.js for Prettier
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      # 2. Install and run Prettier
      - name: Install Prettier
        run: npm install -g prettier
      - name: Check Formatting
        run: prettier --check "**/*.html"
        continue-on-error: true
      - name: Fix Formatting
        run: prettier --write "**/*.html"
      # 3. W3C Validation
      - name: Validate HTML
        uses: docker://validator/validator:latest
        with:
          args: --errors-only --skip-non-html "**/*.html"
      # 4. Commit formatting changes
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Auto-format HTML"
          # Uncomment below if you get permission errors:
          # token: ${{ secrets.GITHUB_TOKEN }}
