name: Format HTML
on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install Prettier
        run: npm install -g prettier
      - name: Check Formatting
        run: prettier --check "**/*.html"
        continue-on-error: true
      - name: Fix Formatting
        run: prettier --write "**/*.html"
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Fix HTML formatting"
