name: Format and Validate HTML
on: [push, pull_request]

jobs:
  format-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup Node for Prettier
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      # Prettier Steps
      - name: Install Prettier
        run: npm install -g prettier
      - name: Check Formatting
        run: prettier --check "**/*.html"
        continue-on-error: true
      - name: Fix Formatting
        run: prettier --write "**/*.html"
      # W3C Validation
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download W3C Validator
        run: |
          wget -q https://github.com/validator/validator/releases/latest/download/vnu.jar
          chmod a+x vnu.jar
      - name: Validate HTML
        run: |
          java -jar vnu.jar --errors-only --skip-non-html "**/*.html"
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Fix HTML formatting"
